# Generated by Django 5.1 on 2024-08-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfirmation',
            name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='userconfirmation',
            name='is_confirmed',
        ),
    ]
